myapp/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from myapp import views as myapp_view

app_name = "myapp"

urlpatterns = [
    path('', myapp_view.home, name='home'),
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='login'), name='logout'),
    path('list/', myapp_view.list, name='list'),
    path('download/', myapp_view.download, name='download'),
    path('home/', myapp_view.home, name='home'),
]

myproject/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [

    path('admin/', admin.site.urls),
    path('', include('myapp.urls', namespace='myapp')),
    path('rest/', include('rest.urls', namespace='rest')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) \
  + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

rest/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path
from rest_framework.authtoken.views import obtain_auth_token

from rest.views import DocViewSet

app_name = 'rest'

urlpatterns = [
    path("list/", DocViewSet.as_view()),
    path('api-token-auth/', obtain_auth_token)
]

myapp/models.py
from django.contrib.auth.models import User
from django.db import models


class Doc(models.Model):
    url = models.CharField(max_length=1000, blank=True)
    body = models.CharField(max_length=5000, blank=True)
    hashtags = models.CharField(max_length=1000, blank=True)
    comkeywords = models.CharField(max_length=1000, blank=True)
    diffkeywords = models.CharField(max_length=1000, blank=True)
    socialsharesReddit = models.CharField(max_length=1000, blank=True)
    socialsharesGoogle = models.CharField(max_length=1000, blank=True)
    socialsharesFb = models.CharField(max_length=1000, blank=True)
    socialsharesLinkedin = models.CharField(max_length=1000, blank=True)
    simscore = models.CharField(max_length=100, blank=True)
    firstLine = models.CharField(max_length=1000, blank=True)
    socialshares_temp = models.CharField(max_length=1000, blank=True)

    class Meta:
        ordering = ['-simscore']


class UserProfile(models.Model):
    # This field is required.
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username

myapp/forms.py
# -*- coding: utf-8 -*-

from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class DocumentForm(forms.Form):
    docfile = forms.FileField(label='Select a file')

myapp/views.py
import os
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.core.files.storage import FileSystemStorage
from django.http import HttpResponse, Http404
from django.shortcuts import render

from .models import Doc
from .driver import *


@login_required
def home(request):
    return render(request, 'main.html')


@login_required
def list(request):
    if request.method == 'POST' and request.FILES['myfile']:
        myfile = request.FILES['myfile']
        fs = FileSystemStorage()
        fs.save(myfile.name, myfile)
        uploaded_file_url = fs.path(myfile.name)
        filtered_res = drive(uploaded_file_url)
        entries = []
        for e in filtered_res.T.to_dict().values():
            entries.append(Doc(**e))
        Doc.objects.all().delete()
        Doc.objects.bulk_create(entries)
        documents = Doc.objects.all()
        return render(request, 'dashboard.html',
                      {
                          'documents': documents,
                          'output_filename': settings.OUTPUT_FILENAME
                      }
                      )

    return render(request, 'main.html')


def download(request):
    if request.method == 'GET':
        file_path = os.path.join(settings.MEDIA_ROOT, settings.OUTPUT_FILENAME + '.csv')
        if os.path.exists(file_path):
            with open(file_path, 'rb') as fh:
                response = HttpResponse(fh.read(), content_type="application/vnd.ms-excel")
                response['Content-Disposition'] = 'inline; filename=' + os.path.basename(file_path)
                return response
    raise Http404

rest/views.py
from django.core.files.storage import FileSystemStorage
from rest_framework.authentication import TokenAuthentication
from rest_framework.permissions import IsAuthenticated
from rest_framework.status import HTTP_400_BAD_REQUEST
from rest_framework.views import APIView

from myapp.driver import drive
from myapp.models import Doc
from .serializers import DocSerializer
from rest_framework.response import Response


class DocViewSet(APIView):
    authentication_classes = (TokenAuthentication, )
    permission_classes = (IsAuthenticated,)

    def post(self, request):
        if request.FILES.get("file") is None:
            return Response(status=HTTP_400_BAD_REQUEST)
        file = request.FILES['file']
        fs = FileSystemStorage()
        fs.save(file.name, file)
        uploaded_file_url = fs.path(file.name)
        filtered_res = drive(uploaded_file_url)
        entries = []
        for e in filtered_res.T.to_dict().values():
            entries.append(Doc(**e))
        Doc.objects.all().delete()
        Doc.objects.bulk_create(entries)
        queryset = Doc.objects.all()
        serializer = DocSerializer(queryset, many=True)
        return Response(serializer.data)

templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
    <title>NewsBot Application</title>
    <meta name="viewport" content="width = device-width, initial-scale = 1">
    <meta description="viewport" content="NewsBot Application">
    <link rel="stylesheet" href="{% static 'css/materialize.min.css' %}">
    <link href="{% static 'css/jdNextGenIconFont.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/upload.css' %}">
    <link rel="stylesheet" href="{% static 'scss/style.scss' %}">
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,700" rel="stylesheet"/>
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,700" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.css"/>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/5.0.0/normalize.min.css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet"/>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<body class="sidebar-mini">
<nav class="nav-wrapper center" style="left: 0;">
    <!-- Toggle Menu Link -->
    <ul class="left mRight">
        <li class="toggleMenu">
            <a href="#" class="menu-link center-align">
                <div class="bar1"></div>
                <div class="bar2"></div>
                <div class="bar3"></div>
            </a>
        </li>
        <li>

            <div class="brand-logo">
                <a href="/myapp/" class="left-align">
                    <img src="{% static 'images/2adpro.png' %}" alt="logo" href="#">
                </a>
            </div>
        </li>
    </ul>

    <div class="search-container hide-on-med-and-down">
    </div>
    <ul class="right mRight navSideMenu">
        <li class="footer"><a href="{% url 'myapp:logout' %}" class="btn btn-primary btn-small">Logout</a>
    </ul>
</nav>

<aside class="sidebar">
    <div id="sideNav" class="side-menu open">
        <ul class="list tabs" id="sideNavTab">
            <li class="tab">
                <a href="/" id="landingScreen" class="active">
                    <div class="spriteWrap">
                        <span class="menuSprite report"></span>
                    </div>
                    <p>Dashboard</p>
                </a>
            </li>


        </ul>
    </div>
</aside>

<div class="body-overlay"></div>


<!-- landing page -->
<div id="task" style="padding-bottom: 200px;padding-top: 10px; border-left-width: 20px; border-right-width: 100px;">
    {% if user.is_authenticated == false %}
        <a href="{% url 'myapp:login' %}">login</a>
    {% else %}
        <div class="content-body rhs" style="margin-top: 0;">

            {% block content %}
            {% endblock %}
        </div>

    {% endif %}


</div>
<!-- landing page -->


<script type="text/javascript" src="{% static 'js/jquery-2.1.1.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/materialize.js' %}"></script>
<script type="text/javascript" src="{% static 'js/index.js' %}"></script>
{#<script type="text/javascript" src="{% static 'js/upload.js' %}"></script>#}
<script type="text/javascript" src="https://cdn.jsdelivr.net/momentjs/latest/moment.min.js"></script>
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.min.js"></script>
<script type="text/javascript" src="{% static 'js/jquery.nicescroll.js' %}"></script>

</body>
</html>



      

templates/base_login.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>{% block title %}Welcome to Social Media Analytics{% endblock %}</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" type="image/png" href="images/icons/favicon.ico"/>
    <link rel="stylesheet" type="text/css" href="{% static 'css/util.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
</head>
<body>

<div class="limiter">
    <div class="container-login100">
        {% block content %}
        {% endblock %}

    </div>
</div>


<div id="dropDownSelect1"></div>
</body>
</html>

templates/dashboard.html
{% extends 'base.html' %}
{% block content %}
    <hr>
    <div class="container col-sm-12" style="margin-right: 0;margin-left: 0;margin-top: 30px;width: 100%">
        <div class="row" style="margin-bottom: 20px;">
            <p><span>Download Complete Results</span>
                <a href="{% url 'myapp:download' %}">{{ output_filename }}.csv</a></p>
        </div>
        <div class="row" style="overflow: scroll;">
            <div class="panel panel-default" style="">
                <table class="table table-fixed" id="sim-table" style="width: 100%; display:block;">
                    <thead>
                    <tr>
                        <th><p style="font-size: 13px;">News URL</p></th>
                        <th><p style="font-size: 13px; float: left">Summary</p></th>
                        <th><p style="font-size: 13px;">Similarity score</p></th>

                        <th><p class="fa fa-reddit" title="Reddit"> Reddit Shares</p></th>
                        <th><p class="fa fa-google" title="GooglePlus"> G+ Shares</p></th>
                        <th><p class="fa fa-facebook" title="facebook"> FB Shares</p></th>
                        <th><p class="fa fa-linkedin" title="Linkedin"> Ln Shares</p></th>
                    </tr>
                    </thead>
                    <tbody style="height:400px; width: 100%; display:block;">
                    {% for obj in documents %}
                        <tr>
                            <td class="col-xs-3" style=""><a href="{{ obj.url }}" target="_blank" style="font-size: 10px">Click here</a></td>
                            <td class="col-xs-4" style=""><a>{{ obj.firstLine }}</a></td>
                            <td class="col-xs-3" style="">{{ obj.simscore }}</td>
                            <td class="col-xs-3" style=""><a>{{ obj.socialsharesReddit }}</a></td>
                            <td class="col-xs-3" style=""><a>{{ obj.socialsharesGoogle }}</a></td>
                            <td class="col-xs-3" style=""><a>{{ obj.socialsharesFb }}</a></td>
                            <td class="col-xs-3" style=""><a>{{ obj.socialsharesLinkedin }}</a></td>

                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <p style="margin-top: 30px;"><a href="{% url 'myapp:list' %}">Return to home</a></p>
{% endblock %}

templates/list.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>NewsBot Application</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'dist/css/vendor/bootstrap/css/bootstrap.min.css' %}" >
    <link rel="stylesheet" href="{% static 'dist/css/flat-ui.css' %}" >
    <link rel="stylesheet" href="{% static 'docs/assets/css/demo.css' %}" >
    <link rel="shortcut icon" href="{% static 'img/favicon.icon' %}">
  </head>
    {% block javascript %}
     <script src="{% static 'js/jquery-3.1.1.min.js' %}"></script>
     <script src="{% static 'js/bootstrap.min.js' %}"></script>
     <script src="{% static 'js/selectSim.js' %}"></script>
    {% endblock %}  
    <style>
      hr { 
          display: block;
          margin-top: 0.5em;
          margin-bottom: 0.5em;
          margin-left: auto;
          margin-right: auto;
          border-style: inset;
          border-width: 1px;
      } 
      .navbar {
      margin-bottom: 0;
      border-radius: 0;
      }
      .sidenav {
      #padding-top: 20px;
      background-color: #f1f1f1;
      #height: 100%;
      }
      footer {
      background-color: #555;
      color: white;
      padding: 15px;
       }
    .row.content {height: 500px}

      .button {
          background-color: #d9534f; /* Green */
          border: none;
          color: white;
          padding: 15px 32px;
          text-align: center;
          text-decoration: none;
          display: inline-block;
          font-size: 16px;
          margin: 4px 2px;
          cursor: pointer;
      }

      .disabled {
          opacity: 0.6;
          cursor: not-allowed;
        }
</style>
 
    </head>

    <body>

 <nav class="navbar navbar-inverse">
          <div class="container-fluid">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>                        
              </button>
               <a href="#" class="navbar-brand"><img src="{% static 'img/newsbot.png' %}"></a> 
              <!--<a class="navbar-brand" href="#">Logo</a>-->
            </div>
            <div class="collapse navbar-collapse" id="myNavbar">
              <ul class="nav navbar-nav">
               <!-- <li><a href="#">User</a></li> -->
               <li><a href="#"> Social Share Estimator for News Articles </a></li>
               
              </ul>
          </div>
          </div>
      </nav>
    <div class="container-fluid text-center">    
                
        <div class="row content">
          <div class="col-sm-1 sidenav"></div>
          <div class="col-sm-10 text-left"> 
      
  <!-- List of uploaded documents -->
        {% if documents %}
            <ul>
                {% for document in documents %}
                    <li><a href="{{ document.docfile.url }}">{{ document.docfile.name }}</a></li>
                {% endfor %}
            </ul>
        {% else %}
            <p>No documents.</p>
        {% endif %}        
             
            <main>
            {% block content %}
            <!-- Upload form. Note enctype attribute! -->
        <form action="{% url 'myapp:list' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <p>{{ form.non_field_errors }}</p>

            <p>{{ form.docfile.label_tag }} {{ form.docfile.help_text }}</p>

            <p>
                {{ form.docfile.errors }}
                {{ form.docfile }}
            </p>

            <p><input type="submit" value="Upload"/></p>
            <p><input type="submit" value="Submit"/></p>
        </form>
            {% endblock %}
            </main>
          </div> 
          <div class="col-sm-2 sidenav"></div>       
        </div>
        
     </div>
    
  </body>

</html>

templates/login.html
{% extends 'base_login.html' %}


{% block content %}

    <div class="wrap-login100 p-t-50 p-b-90">

        <form method="post" class="login100-form validate-form flex-sb flex-w">
            {% csrf_token %}
            <span class="login100-form-title p-b-51">
						Login
					</span>
            {% if form.errors %}
                <p style="color: red; margin-bottom: 20px;">Your username and password didn't match. Please try again.</p>
            {% endif %}
            <div class="wrap-input100 validate-input m-b-16" data-validate="Username is required">
                <input class="input100" type="text" name="username" placeholder="Username"
                       id="id_username">

                <span class="focus-input100"></span>
            </div>


            <div class="wrap-input100 validate-input m-b-16" data-validate="Password is required">

                <input class="input100" type="password" name="password" placeholder="Password"
                       id="id_password">

                <span class="focus-input100"></span>
            </div>


            <div class="container-login100-form-btn m-t-17">
                <button name="next" class="login100-form-btn" type="submit" value="login">
                    Login
                </button>
                <input type="hidden" name="next" value="{{ next }}"/>
            </div>

        </form>
    </div>
{% endblock %}

templates/main.html
{% extends 'base.html' %}

{% block content %}
    <div>
        <h2 style="margin-bottom: 30px;">File Upload & processing</h2>

        <!-- Upload  -->
        <form method="post" action="{% url 'myapp:list' %}" enctype="multipart/form-data" id="file-upload-form" class="uploader">
            {% csrf_token %}
            <input id="file-upload" type="file" name="myfile" onchange="this.form.submit()"/>
            <label for="file-upload" id="file-drag">
                <div id="start">
                    <i class="fa fa-download" aria-hidden="true"></i>
                    <div>Select a file or drag here</div>
                    <div id="notimage" class="hidden">Please select text file</div>
                    <span id="file-upload-btn" class="btn btn-primary">Select a file</span>
                </div>
                <div id="response" class="hidden">
                    <div id="messages"></div>

                </div>
            </label>
        </form>
    </div>
{% endblock %}